baseURL = "https://sm2026wollerau.ch/"
languageCode = "de-ch"
title = "SM Nationalturnern 2026"

[params]
description = "Schweizer Meisterschaft Nationalturnen 2026"

[menu]
[[menu.main]]
pageRef = "news"
name = "News"
url = "/news/"
weight = 1
[[menu.main]]
pageRef = "wettkampf"
name = "Wettkampf"
url = "/wettkampf/"
weight = 2
[[menu.main]]
pageRef = "fest"
name = "Fest"
url = "/fest/"
weight = 3
[[menu.main]]
pageRef = "partner"
name = "Partner"
url = "/partner/"
weight = 4
[[menu.main]]
pageRef = "organisation"
name = "Organisation"
url = "/organisation/"
weight = 5


