baseURL = "https://sm2026wollerau.ch/"
languageCode = "de-ch"
title = "SM Nationalturnern 2026"

[params]
  description = "Schweizer Meisterschaft Nationalturnen 2026"

[menu]
  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 1
  [[menu.main]]
    identifier = "wettkampf"
    name = "Wettkampf"
    url = "/wettkampf/"
    weight = 2
  [[menu.main]]
    identifier = "organisation"
    name = "Organisation"
    url = "/organisation/"
    weight = 3
  [[menu.main]]
    identifier = "fest"
    name = "Fest"
    url = "/fest/"
    weight = 4

